### ISSUE TITLE
Enable CORS

### ISSUE THREAD

**Issue by eek** [gertjaap/vtc-wallet-middleware-cpp#10]
I'm trying to build a small service on what's already up, `https://vtc.blkidx.org`, but unfortunately CORS is not enabled.

> Failed to load https://vtc.blkidx.org/addressBalance/Vg8APdm2BhFbaZuTsXnG8Ny66k1YfnvurQ?details=1: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Can we add something like this:

> cors_header.name = "Access-Control-Allow-Origin";
> cors_header.value = "*"; //allow requests from any domain;

in the CORS Headers from the Server Response?

I couldn't find anything useful in `libjson-rpc-cpp`

**Comment by gertjaap** [comment]
Yeah i can do that.

**Comment by gertjaap** [comment]
I committed this a while ago, forgot to update the issue. Can you check?
