### ISSUE TITLE
GraphQL?

### ISSUE THREAD

**Issue by eek** [gertjaap/vtc-wallet-middleware-cpp#11]
Testing the API, I realize that my needs are a bit different than how this API is built and each devs needs might be also be different.

Have you guys considered implementing GraphQL for this API? http://graphql.org/

Where the user request exactly what they need? 😁 

There's also a GraphQL Query Parser built for C++  - https://github.com/graphql/libgraphqlparser

**Comment by gertjaap** [comment]
We're not having a full indexed SQL backend to this. So we shouldn't support a free query language since it would give the impression that you can query anything, when in reality most queries would be unsupported.
