### ISSUE TITLE
outpointSpend returns false instead of errors

### ISSUE THREAD

**Issue by adiabat** [gertjaap/vtc-wallet-middleware-cpp#7]
The outpointSpend RPC will return a 404 error if the URL string is malformed, for example if you put a "g" in the hex string and it can't decode it as hex.

However if you put a random hex string, even one which is too short, for example `https://vtc.xchan.gr/new/outpointSpend/0/0`, it will return `{"spent":false}`.  This sortof makes sense as outpoint 0:0 isn't "spent" because it doesn't exist, but maybe it should return some kind of error instead of just saying "false".  This would help with debugging as right now an invalid or non-existent outpoint won't trigger any errors.

**Comment by gertjaap** [comment]
I changed the API to return an error when you use a non-existing transaction ID

**Comment by adiabat** [comment]
Cool, thanks!  Will close this

**Comment by adiabat** [comment]
Cool, thanks!  Will close this

**Comment by adiabat** [comment]
Cool, thanks!  Will close this
